
temp <- list.files(recursive = TRUE, path="C:/Users/raoda/AppData/Local/R/win-library/4.2" )
temp <- as.data.frame(tmp)
install.packages(c("patchwork", "yulab.utils"))
install.packages(c("cluster", "foreign", "KernSmooth", "lattice", "Matrix", "mgcv", "nlme", "rpart", "spatial", "survival"), lib="C:/Program Files/R/R-4.3.1/library")
install.packages(c("patchwork", "yulab.utils"))
install.packages(c("cluster", "foreign", "KernSmooth", "lattice", "Matrix", "mgcv", "nlme", "rpart", "spatial", "survival"), lib="C:/Program Files/R/R-4.3.1/library")
readRDS("R Projects/temporary.RDS")
temp <- readRDS("R Projects/temporary.RDS")
library("tidyverse")
.libPaths()
.libPaths("C:/Program Files/R/R-4.3.2/library")
.libPaths()
temp %>% separate(temp,into = c("file","extension","NA"),sep = "/")
temp <- temp %>% separate(temp,into = c("file","extension","NA"),sep = "/")
temp <- distinct(file)
temp <- temp %>% distinct(file)
View(temp)
install.packages(temp$file)
install.packages(temp$file)
install.packages(temp$file)
install.packages(temp$file)

.libPaths(c("C:/Users/raoda/AppData/Local/R/win-library/4.3","C:/Program Files/R/R-4.3.2/library","C:/Program Files/R/R-4.3.1/library"), include.site = TRUE)

